fs_fishfeeds:
    resource: "@FsBundle/Resources/config/routing/fishfeeds.yml"
    prefix:   /fishfeeds

fs_fish:
    resource: "@FsBundle/Resources/config/routing/fish.yml"
    prefix:   /fish

fs_homepage:
    path:     /
    defaults: { _controller: FsBundle:Default:index }
