fishfeeds:
    path:     /
    defaults: { _controller: "FsBundle:FishFeeds:index" }

fishfeeds_show:
    path:     /{id}/show
    defaults: { _controller: "FsBundle:FishFeeds:show" }

fishfeeds_new:
    path:     /new
    defaults: { _controller: "FsBundle:FishFeeds:new" }

fishfeeds_create:
    path:     /create
    defaults: { _controller: "FsBundle:FishFeeds:create" }
    methods:  POST

fishfeeds_edit:
    path:     /{id}/edit
    defaults: { _controller: "FsBundle:FishFeeds:edit" }

fishfeeds_update:
    path:     /{id}/update
    defaults: { _controller: "FsBundle:FishFeeds:update" }
    methods:  [POST, PUT]

fishfeeds_delete:
    path:     /{id}/delete
    defaults: { _controller: "FsBundle:FishFeeds:delete" }
    methods:  [POST, DELETE]
